### PR TITLE
CI and PHPUnit

### PR DESCRIPTION
**Pull request by sanmai**
- [x] Basic PHPUnit test case added with all existing fixtures. They're not yet checked pixel to pixel, as fixtures need an update.
- [x] `die()` replaced with `throw new Exception` in some places
- [x] Config for Travis CI added [(confirmation)](https://travis-ci.com/sanmai/libchart-1/builds/129619052)
- [x] Tests work under PHP 7.0+

This can be merged as it is.

Next I will check that updated fixtures are indeed correct, updated them while enabling proper pixel to pixel assertions. After that I guess the good idea would to be to deal with CS on CI.

### CODE REVIEW

**Comment by sanmai** [comment]
@astehlik if there's anything wrong with this PR, please let me know

**Comment by astehlik** [comment]
Thank you :)

I did some reformatting in the tests and integrated Code Climate instead of Coverall because I already had an account there ;)

**Comment by sanmai** [comment]
Please see my review on #6. Don't be afraid to ask for a review.

What do you prefer to use for CS? I'm not a big fan of PHP_CodeSniffer tbh, for one because it is not as flexible as PHP-CS-Fixer. If you absolutely insist on using PHP_CodeSniffer, we'll roll with it for time being.

**Comment by astehlik** [comment]
I do not have a passionate opinion about PHP-CS-Fixer oder PHP_CodeSniffer. I recently did some research on that topic and some people advocate to use them both.

In the past I only used PHP_CodeSniffer so I know how to configure it. Also: Code Climate only seems to have a plugin for phpcs, not for PHP-CS-Fixer.

I'm totally fine with integrating PHP-CS-Fixer additionally. Is there a good was to do this for GitHub? I would imagine something like automatically adding a commit to a pull request that fixes code style errors.

If you experience any problems with the current phpcs integration in Code Climate I can adjust the configuration as needed. Please let me know :)

**Comment by sanmai** [comment]
There's PrettyCI which integrates nicely with GitHub statuses and such. I really like how they did it. As for the configuration, I can make it.

It won't update the code for you, God forbid. We are all sentient human beings here, able to run a command to fix own code.

**Pull request merged**
