### PR TITLE
Rename phpunit.xml to phpunit.xml.dist

### PR DESCRIPTION
**Pull request by sanmai**
Renaming `phpunit.xml.dist` to `phpunit.xml` is a problem. I use my own `phpunit.xml` with coverage options and such, and it is very helpful to have to be able to use `git commit -a` sometimes.

It is also very annoying to have to revert changes `phpunit.xml` if you happen to forget that you can't use `git commit -a` in this repository. And also annoying having to skip changes to `phpunit.xml` when you do `git add -p`. 

Otherwise put, it is annoying all around not being able to override the configuration.

### CODE REVIEW

**Comment by sanmai** [comment]
There's one build failing because of some Code Climate issue.

**Comment by astehlik** [comment]
I really like having the main `phpunit.xml` file in the project root directory. This allows anyone to just punch in `phpunit` and the tests will run. Do you have the possibility to provide your special configuration file via commandline? Like

```
phpunit -c phpunit.special.xml
```
You can also add your `phpunit.special.xml` to `.git/info/exclude`. In that way you can name it whatever you want and it will never be added to git.

If that is not an option for you, I will merge this change.

**Comment by sanmai** [comment]
PHPUnit knows about `phpunit.xml.dist` and automatically picks it up if present. You don't need to rename it or copy to `phpunit.xml`, it's just works. [It's a known documented feature.](https://phpunit.readthedocs.io/en/8.3/organizing-tests.html#composing-a-test-suite-using-xml-configuration)

There's no harm in having  `phpunit.xml.dist`, but on the other hand there's a certain inconvenience in a plain `phpunit.xml` without `.dist`.

**Comment by astehlik** [comment]
> PHPUnit knows about phpunit.xml.dist and automatically picks it up if present. It's a known documented feature.

I guess you never stop learning. Thanks for the hint :)

**Comment by sanmai** [comment]
Thank you.

**Pull request merged**
