### PR TITLE
Silence count() warning

### PR DESCRIPTION
**Pull request by sanmai**
Silence "Parameter must be an array or an object that implements Countable" for time being.

### CODE REVIEW

**Comment by sanmai** [comment]
@astehlik is there anything that can be done to accept or review this PR or #3? Debian stable already has PHP 7.3, and it gives warnings all over the place. Very annoying.

**Comment by sanmai** [comment]
Just as well I can assume a maintainer role if you wish as I have experience maintaining several project here on GitHub.

**Comment by astehlik** [comment]
Hi and thanks for your contribution.

I merged #3 so I close this one because it seems to do the same thing ;)

**Comment by sanmai** [comment]
That's fair. I wonder if you're willing to review additional pull requests. Or maybe you're willing to add me as a maintainer. FWIW I'm a maintainer for some projects already.

**Comment by astehlik** [comment]
You are welcome to create pull requests and I try to merge them ASAP.

**Comment by sanmai** [comment]
All right, will the #4 work for you?

I got to be adding testing and CI before all things, but that'll come later.

**Pull request closed without merging**
